docker-compose-yaml: docker-compose.yml

api: https://api.salsa.hosting/graphql
ssh: ssh.salsa.hosting:22

project: lagoon-drupal-example

tasks:
  pre-rollout:
    - run:
        name: run custom pre-rollout tasks
        command: ahoy my pre-rollout
        service: cli

  post-rollout:
    - run:
        name: run custom post-rollout tasks
        command: ahoy my post-rollout
        service: cli

environments:
  main:
    routes:
      -
        nginx:
          -
            d3vaie88ppi09b.cloudfront.net:
              tls-acme: 'false'
              inseure: Allow
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
