ARG CLI_IMAGE
ARG IMAGE_VERSION=latest

FROM ${CLI_IMAGE} as cli

FROM uselagoon/nginx:${IMAGE_VERSION}

COPY .docker/nginx/nginx.conf /etc/nginx/conf.d/app.conf
# Adding Stagefile helper
COPY .docker/nginx/stagefile-*.conf /etc/nginx/conf.d/wordpress/

COPY --from=cli /app /app

# Define where the Drupal Root is located
ENV WEBROOT=web
